1200D: Sync internal.h with 1100D since both are almost similar
This also solves the following errors

../../src/task_utils.c: In function 'get_current_task_name':
../../src/task_utils.c:14:28: error: dereferencing pointer to incomplete type 'struct task'
         return current_task->name;
                            ^~
../../src/task_utils.c: In function 'get_task_name_from_id':
../../src/task_utils.c:49:12: error: variable 'task_attr' has initializer but incomplete type
     struct task_attr_str task_attr = {0};

After the defining the following configs

Signed-off-by: Bhargav Das <bhargavdas100@gmail.com>